{{-- 
  Listo Logo generated by copy pasting svg in this website: https://jakearchibald.github.io/svgomg/ 
  tutorial found here https://tailwindcss.com/course/working-with-svg-icons

  for the logout = https://wordpress.stackexchange.com/questions/67336/how-to-log-out-without-confirmation-do-you-really-want-to-log-out
  --}}
<header class="flex items-center justify-between bg-gray-900 px-2 py-3">
  <div>
    <a href="{{ home_url('/') }}" class="focus:outline-none hover:no-underline hover:text-white">
      {{-- <img src="@asset('images/listo_logo.svg')" width="30" alt="listo logo"> --}}
      <svg class="h-8 w-8 inline fill-current text-red-800" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600">
        <path d="M364.66 58.64c-40.69-6.7-92.81-3.31-130.34 9.73l-12.29-29.18L140.19 130l120.4.76-11.39-27.04c121.67-29.7 263.18 27.99 259.54 216.63-1.85 95.97-87.63 186.22-205.19 198.54-4.14 0-7.49 3.35-7.49 7.49 0 4.14 3.35 7.49 7.49 7.49.14 0 .27-.03.41-.04v.04c107.5-4.97 215.44-82.51 235.59-211.23 18.78-119.96-54.09-244.11-174.89-264zM268.97 516.03c-4.82 0-8.73 3.91-8.73 8.73s3.91 8.73 8.73 8.73 8.73-3.91 8.73-8.73-3.91-8.73-8.73-8.73zM234.19 510.21c-4.19 0-7.59 3.4-7.59 7.59 0 4.19 3.4 7.59 7.59 7.59s7.59-3.4 7.59-7.59c0-4.19-3.4-7.59-7.59-7.59z" /><circle cx="200.77" cy="506.04" r="6.6" /><circle cx="169.69" cy="488.93" r="6.6" /><circle cx="141.44" cy="467.35" r="6.6" /><circle cx="116.91" cy="441.74" r="6.6" /><g><circle cx="96.5" cy="412.64" r="6.6" /><circle cx="80.87" cy="380.99" r="6.6" /><circle cx="70.26" cy="347.02" r="6.6" /><circle cx="65.04" cy="312.04" r="6.6" /><circle cx="65.04" cy="276.6" r="4.44" /><path d="M70.31 244.63c1.61 0 2.91-1.3 2.91-2.91s-1.3-2.91-2.91-2.91-2.91 1.3-2.91 2.91 1.31 2.91 2.91 2.91z" /></g><g><path d="M256.66 453.18c-3.94 0-7.92-1.07-11.5-3.33-5.03-3.18-15.69-8.97-16.9-18.63-1.21-9.66 7.03-23.19 10.21-28.22l153.76-226.19c6.35-10.06 19.66-13.04 29.72-6.7 10.06 6.35 13.06 19.66 6.69 29.72L274.88 443.15c-4.1 6.49-11.08 10.03-18.22 10.03z" /></g><path d="M232.67 391.1l11.64-17.52-52.43-81.66c-5.79-10.4-13.96-13.47-24.36-7.7-10.39 5.78-10.02 15.3-4.23 25.7l58.1 113.96c-2.45-14.95 11.28-32.78 11.28-32.78z" />
      </svg>
      <span class="text-white text-xl">&nbsp;Listo</span><span class="text-red-800 text-xl">&nbsp;World</span>
    </a>
  </div>
  <div>
    @if ( is_user_logged_in() )
    @php
    $user = wp_get_current_user();
    $logout_url = site_url() . "/wp-login.php?action=logout";
    @endphp
    <a href="{{ esc_url(bloginfo('url')) }}/profile/{{ $user->display_name }}"
      class="inline-block h-8 w-8 rounded-full overflow-hidden align-middle focus:outline-none border-2 border-gray-800 hover:border-gray-600">
      <img class="h-full w-full object-cover" src="{{ get_avatar_url( $user->user_email) }}"
        alt="{{ $user->display_name }}">
    </a>
    <a href="{{ esc_url($logout_url) }}" class="text-white hover:text-gray-600 align-middle text-xl ml-3"><i
        class="fas fa-sign-out-alt"></i></a>
    @else
    <a href="{{ esc_url(bloginfo('url'))}}/login" class="text-white text-md align-middle">Sign in <i
        class="fas fa-sign-in-alt"></i></a>
    <a href="{{ esc_url(bloginfo('url'))}}/wp/wp-login.php?action=register" class="text-white text-md align-middle mx-2">Sign up <i class="fas fa-user-plus"></i></a>
    @endif
    <a href="#offcanvas-slide" class="text-white text-lg align-middle mx-3 hover:text-gray-600" uk-toggle><i
        class="fas fa-bars"></i></a>
  </div>
</header>

<div id="offcanvas-slide" uk-offcanvas>
  <div class="uk-offcanvas-bar">

    {{-- <ul class="uk-nav uk-nav-default">
      <li class="uk-active"><a href="#">Enquiry</a></li>
      <li><a href="#">Latest Posts</a></li>
      <li><a href="#">Account</a></li>
      <li><a href="#">My list</a></li>
      <li class="uk-nav-header">About Us</li>
      <li><a href="#">Our mission</a></li>
      <li><a href="#">Vision</a></li>
      <li><a href="#">Values</a></li>
      <li><a href="#">Terms and Conditions</a></li>
      <li class="uk-nav-divider"></li>
      <li><a href="#">Item</a></li>
    </ul> --}}
    <span class="text-xl text-white text-bold">Menu</span>
    <hr>
    @if (has_nav_menu('primary_navigation'))
    {!! wp_nav_menu(['theme_location' => 'primary_navigation', 'menu_class' => 'uk-nav uk-nav-default']) !!}
    @endif
    </nav>

  </div>
</div>




{{-- code for the account and submenu --}}

{{-- <div class="inline relative">
  <button id="account-button" class="inline-block h-8 w-8 rounded-full overflow-hidden align-middle focus:outline-none border-2 border-gray-800 hover:border-gray-600">
    <img class="h-full w-full object-cover" src="{{ get_avatar_url( $user->user_email) }}"
alt="{{ $user->display_name }}">
</button>
<div id="account-submenu" class="hidden absolute right-0 w-40 py-1 mt-2 bg-white rounded-lg shadow-xl z-10">
  <a href="{{ esc_url(bloginfo('url')) }}/profile/{{ $user->display_name }}"
    class="block px-4 py-1 text-gray-800 hover:bg-gray-600 hover:text-gray-300 hover:no-underline">Dashboard</a>
  <a href="" class="block px-4 py-1 text-gray-800 hover:bg-gray-600 hover:text-gray-300 hover:no-underline">Account
    Settings</a>
  <a href="" class="block px-4 py-1 text-gray-800 hover:bg-gray-600 hover:text-gray-300 hover:no-underline">Support</a>
  <a href="{{ $logout_url }}"
    class="block px-4 py-1 text-gray-800 hover:bg-gray-600 hover:text-gray-300 hover:no-underline">Log out</a>
</div>
</div>
<i class="fas fa-user-circle"></i>
--}}


